### ISSUE TITLE
Add 'anonymous_children' to _READONLY_PROPERTIES

### ISSUE THREAD

**Issue by stanrogo** [applitools/eyes.selenium.python#2]
While attempting to finally get Firefox working with geckodriver, I ran into the issue where I got the message 'Strategy not supported: anon'.

I dived deeper into the source code and apparently the WebElement passed to EyesWebElement has the attribute 'anonymous_children', now I don't know if this is perhaps version incompatibility between my browser (50.0.2), selenium (3.0.2) and applitools (3.5), but if I add it to the read only properties list then this resolves my issue entirely.

I may be definitely not aware of the fact that perhaps this attribute is needed somehow, or shouldn't be there in the first place at all, but it seems to have resolved the issue. Would you know more about this, or if adding this doesn't have any negative consequences?

**Comment by danielputerman** [comment]
Nice catch! Adding the property to the READONLY_PROPERTIES is the correct solution. 
Adding the property to the list does not remove the attribute in any way. It simply tells the Applitools dynamic interface creation process that it should be aware that this attribute is a property, so it needs to be handled a bit differently than a standard attribute.

**Comment by danielputerman** [comment]
Fixed in commit f9119fe29ec8de329baa84bc5d63f120b61a64b9.
